name: Bug Report
description: Submit bug report.
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. At first do ...
        2. Then do ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What actually happened?
      placeholder: Not OK
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: What did you expect to happen?
      placeholder: OK
    validations:
      required: true
