name: Feature request
description: Suggest an idea for this project.
title: "Add "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank for your attention to project!
  - type: textarea
    id: related
    attributes:
      label: Is your feature request related to a problem
      description: Please describe
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
