[package]
name = "tutti-types"
description = "DTO for Tutti"
repository = "https://github.com/ya7on/tutti"
version = "0.1.3"
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
